//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoenixUsers
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSC
    {
        public int ID { get; set; }
        public int BranchID { get; set; }
        public string UserName { get; set; }
        public int UserID { get; set; }
        public string TermID { get; set; }
        public int UID { get; set; }
        public bool AllowFC { get; set; }
        public bool isActive { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual UserMasterData UserMasterData { get; set; }
    }
}
