//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoenixUsers
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMasterData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserMasterData()
        {
            this.ADUsers = new HashSet<ADUser>();
            this.KSCs = new HashSet<KSC>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public int BranchID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string PharmosUserName { get; set; }
        public string UADMUserName { get; set; }
        public Nullable<bool> GI { get; set; }
        public Nullable<bool> Purchase { get; set; }
        public Nullable<bool> Tender { get; set; }
        public Nullable<bool> Phibra { get; set; }
        public bool Active { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADUser> ADUsers { get; set; }
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KSC> KSCs { get; set; }
        public virtual Position Position { get; set; }
    }
}
