//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoenixUsers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserDBEntities : DbContext
    {
        public UserDBEntities()
            : base("name=UserDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADUser> ADUsers { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<KSC> KSCs { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<UserMasterData> UserMasterDatas { get; set; }
        public virtual DbSet<AD_User_Group> AD_User_Groups { get; set; }
    }
}
